apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deny
  namespace: namespace-a
  labels:
    app: web-deny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deny
  template:
    metadata:
      labels:
        app: web-deny
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: namespace-a
spec:
  podSelector:
    matchLabels:
      app: web-deny
  policyTypes:
    - Ingress

